# Generated by Django 2.2.3 on 2021-04-18 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_maquina', models.CharField(max_length=55)),
                ('Nombre_maquina', models.CharField(blank=True, max_length=55)),
            ],
        ),
        migrations.DeleteModel(
            name='Propina',
        ),
    ]
