# Generated by Django 2.2.3 on 2021-04-18 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_auto_20210418_1847'),
    ]

    operations = [
        migrations.RenameField(
            model_name='validacion',
            old_name='usuario',
            new_name='user',
        ),
    ]
