# Generated by Django 2.2.3 on 2021-04-18 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_auto_20210418_1915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maquina',
            name='id_maquina',
        ),
    ]
