# Generated by Django 2.2.3 on 2021-04-23 10:22

from django.db import migrations, models
import usuarios.models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_activiadad_entrenamiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquina',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=usuarios.models.upload_maquina),
        ),
        migrations.AlterField(
            model_name='activiadad',
            name='fecha',
            field=models.DateTimeField(),
        ),
    ]
