# Generated by Django 2.2.3 on 2021-04-23 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_auto_20210423_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquina',
            name='slug',
            field=models.SlugField(default=None, editable=False),
            preserve_default=False,
        ),
    ]
