# Generated by Django 2.2.3 on 2021-04-24 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_activiadad_entrenamiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activiadad',
            name='entrenamiento',
        ),
    ]
