# Generated by Django 2.2.3 on 2021-04-28 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_remove_activiadad_entrenamiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrenamiento',
            name='fecha',
            field=models.DateTimeField(),
        ),
    ]
