# Generated by Django 2.2.3 on 2021-04-28 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_auto_20210428_0114'),
    ]

    operations = [
        migrations.AddField(
            model_name='activiadad',
            name='nombre_activida',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
    ]
