# Generated by Django 2.2.3 on 2021-04-28 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0012_activiadad_nombre_activida'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrenamiento',
            name='maquina',
        ),
        migrations.AddField(
            model_name='entrenamiento',
            name='Nombre_maquina',
            field=models.CharField(blank=True, max_length=55),
        ),
    ]
