# Generated by Django 2.2.3 on 2021-04-28 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0013_auto_20210428_1351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrenamiento',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='activiadad',
            name='descripcion',
            field=models.CharField(blank=True, max_length=240, null=True),
        ),
    ]
