# Generated by Django 2.2.3 on 2021-04-28 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0017_auto_20210428_1823'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activiadad',
            old_name='nombre_activida',
            new_name='nombre_actividad',
        ),
    ]
