# Generated by Django 2.2.3 on 2021-04-28 18:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuarios', '0018_auto_20210428_1841'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Activiadad',
            new_name='Actividad',
        ),
    ]
