# Generated by Django 2.2.3 on 2021-05-01 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0022_auto_20210428_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrenamiento',
            name='hora',
            field=models.TimeField(default=None),
            preserve_default=False,
        ),
    ]
