# Generated by Django 2.2.3 on 2021-05-01 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0023_entrenamiento_hora'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_anuncio', models.CharField(blank=True, max_length=55, null=True)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('descripcion', models.CharField(blank=True, max_length=240, null=True)),
                ('precio', models.IntegerField(default=0)),
            ],
        ),
    ]
