# Generated by Django 2.2.3 on 2021-05-01 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0025_anuncio_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Misanuncios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_anuncio', models.CharField(blank=True, max_length=55, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=240, null=True)),
            ],
        ),
    ]
