# Generated by Django 2.2.3 on 2021-05-01 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0027_misanuncios_usuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Misanuncios',
        ),
    ]
