# Generated by Django 2.2.3 on 2021-05-01 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0028_delete_misanuncios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anuncio',
            name='slug',
        ),
        migrations.AddField(
            model_name='anuncio',
            name='image',
            field=models.ImageField(default=None, upload_to=''),
            preserve_default=False,
        ),
    ]
