# Generated by Django 2.2.3 on 2021-05-02 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0029_auto_20210501_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrenamiento',
            name='descripcion',
            field=models.CharField(blank=True, max_length=240, null=True),
        ),
    ]
