# Generated by Django 2.2.3 on 2021-05-25 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0032_transaccion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anuncio',
            name='pagado',
        ),
        migrations.AddField(
            model_name='transaccion',
            name='anuncio',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.Anuncio'),
            preserve_default=False,
        ),
    ]
